FROM openjdk:11
VOLUME /tmp

EXPOSE 8080 5005

ARG JAR_FILE=target/iter-0.0.1-SNAPSHOT.jar
ADD ${JAR_FILE} iter.jar

ENTRYPOINT ["java","-Djava.security.egd", "-Xdebug","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005","-jar","/iter.jar"]